INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'abhinav@gmail.com', 'abhinav', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'abhishek@gmail.com', 'abhishek', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'abhijat@gmail.com', 'abhijat', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'abhi@gmail.com', 'abhi', 'ADMIN');