INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Fabric Sofa', '16499', 'Bali 2 Seater - Pink', 'FURNITURE', 'sofa_1.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Floral Carpet', '900', 'Best Carpet', 'CARPETS', 'carpet_1.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Soft Foam Mattress', '4274', '3 Folding Mattress', 'BEDS AND MATTRESSES', 'mettress_1.jpg', 45);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Flora Kids 2 Door Wardrobe', '20000', 'Best Wardrobe', 'STORAGE', 'storage_1.jpg', 40);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Jute Carpet ', '1500', 'Best Carpet', 'CARPETS', 'carpet_2.jpg', 35);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'SOLARA Single Bed', '15000', 'Best Bed', 'BEDS AND MATTRESSES', 'mattress_2.jpg', 30);

INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Fabric 2 Seater Sofa', '14249', 'Best Sofa', 'FURNITURE', 'sofa_2.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Azealia Reclaimed Wood Sideboard', '12000', 'Best Storage', 'STORAGE', 'storage_2.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Adele Reclaimed Wood Sideboard', '15000', 'Best Storage', 'STORAGE', 'storage_3.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Alen 6 Seater Fabric Sofa', '34299', ' 6 Seater Fabric Sofa','FURNITURE', 'sofa_3.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Super Softness Floral Design Carpet', '2200', 'Best Carpet', 'CARPETS', 'carpet_3.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Queen Metal Bed', '7000', 'Best Bed', 'BEDS AND MATTRESSES', 'bed_1.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Plastic Sheet Wardrobe', '3789', 'Wardrobe Storage for Clothes Kids', 'STORAGE', 'storage_6.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Wooden Dining Chair', '5999', 'Best Chair', 'FURNITURE', 'chair_1.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Slim Foldable Mattress', '1700', 'Best Mattress', 'BEDS AND MATTRESSES', 'mattress_3.jpg', 30);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Carpet Plus Shaggy', '5849', 'Carpet Plain Fur Rugs for Bedroom Living Room', 'CARPETS', 'carpet_4.jpg', 50);

INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'E-Furniture Bed ', '18299', 'Home Bed', 'TOP_OFFERS', 'top_offer_1.jpg', 50);

INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Engineered Wood Wardrobe', '18199', '4 Doors Wardrobe', 'TOP_OFFERS', 'top_offer_2.jpg', 45);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Wool Soft and Thick Carpet', '4000', 'Best Carpet', 'TOP_OFFERS', 'top_offer_3.jpg', 50);
