CREATE SEQUENCE HIBERNATE_SEQUENCE
start with 1
increment by 1;

CREATE TABLE PRODUCTS (
	PRODUCT_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR2(100) NOT NULL,
	PRICE VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(500) NOT NULL,
	CATEGORY VARCHAR2(100) NOT NULL,
	IMAGE_URL VARCHAR2(100) NOT NULL,
	STOCK INTEGER NOT NULL);